/**
 * Whitelist des champs `flanges` modifiables via PATCH/POST côté API.
 * Partagé entre `/api/flanges` (CRUD desktop) et `/api/terrain/sync`
 * (filtre des champs initiaux à la création hors-ligne).
 *
 * Les colonnes GENERATED (delta_dn, delta_pn, *_retenu) sont volontairement
 * absentes — elles sont calculées par Postgres.
 */
export const FLANGES_ALLOWED = new Set([
  "nom",
  "zone",
  "famille_travaux",
  "type",
  "repere_buta",
  "repere_emis",
  "repere_ubleam",
  "commentaire_repere",
  "dn_emis",
  "dn_buta",
  "pn_emis",
  "pn_buta",
  "operation",
  "barrette",
  "nb_jp_emis",
  "nb_jp_buta",
  "nb_bp_emis",
  "nb_bp_buta",
  "materiel_emis",
  "materiel_buta",
  "materiel_adf",
  "cle",
  "nb_tiges_emis",
  "nb_tiges_buta",
  "matiere_tiges_emis",
  "matiere_tiges_buta",
  "dimension_tige_emis",
  "dimension_tige_buta",
  "nb_joints_prov_emis",
  "nb_joints_prov_buta",
  "nb_joints_def_emis",
  "nb_joints_def_buta",
  "matiere_joint_emis",
  "matiere_joint_buta",
  "rondelle_emis",
  "rondelle_buta",
  "face_bride_emis",
  "face_bride_buta",
  "commentaires",
  "num_rob",
  "rob_side",
  "amiante_plomb",
  "operation_buta",
  "securite_buta",
  "sap_buta",
  "responsable",
  "calorifuge",
  "echafaudage",
  "echaf_longueur",
  "echaf_largeur",
  "echaf_hauteur",
  "field_status",
]);
